spring:
  application:
    name: ai_gen_web_backend
  # session
  session:
    store-type: redis
    timeout: 2592000
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.miao.ai_gen_web.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# prometheus
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
