spring:
  application:
    name: meow-draw-user
  # session
  session:
    store-type: redis
    timeout: 2592000

  # redis
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      user: default
      password: 123456
      ttl: 3600
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_gen_web
    username: root
    password: 123456

server:
  port: 8124
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.miao.ai_gen_web.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# Dubbo
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    register-mode: instance
  protocol:
    name: tri  # 这代表 Triple 协议。  它是 Dubbo 3.0 的主力协议，基于 gRPC (HTTP/2) 编写。
    port: 50051
  consumer:
    timeout: 60000
  provider:
    timeout: 60000

